<a href="https://colab.research.google.com/github/GiaHan2702/lab2/blob/main/Copy_of_lab2_ex2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Gaussian Naive

In [ ]:
import numpy as np
import statistics as st

In [ ]:
features = np.array([[4.9,     3], 
                    [4.7, 3.2], 
                    [4.6, 3.1], 
                    [5,  3.6], 
                    [5.4, 3.9],
                    [4.6, 3.4], 
                    [6.4, 3.2], 
                    [6.9,  3.1], 
                    [5.5, 2.3],  
                    [6.5, 2.8],         
                    [5.7, 2.8], 
                    [6.3, 3.3], 
                    [5.6,  2.2], 
                    [5.1, 1.5],
                    [5.6, 1.4], 
                    [5.9, 2.1], 
                    [5.3,  1.8],   
                    [5.7, 1.9]
                     ])
x0l=np.array([4.9, 4.7, 4.6, 5, 5.4,4.6])
x1l=np.array([6.4, 6.9, 5.5, 6.5, 5.7, 6.3])
x2l=np.array([5.6, 5.1, 5.6, 5.9, 5.3, 5.7])

x0w=np.array([3, 3.2, 3.1, 3.6, 3.9, 3.4])
x1w=np.array([3.2, 3.1, 2.3, 2.8, 2.8, 3.3])
x2w=np.array([2.2, 1.5, 1.4, 2.1, 1.8, 1.9])

labels = np.array([[0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   ])

X = np.array([[5.2, 2.4]])

print(features)
print(labels)
print(x0l)
print(X)

[[4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [5.6 2.2]
 [5.1 1.5]
 [5.6 1.4]
 [5.9 2.1]
 [5.3 1.8]
 [5.7 1.9]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
[4.9 4.7 4.6 5.  5.4 4.6]
[[5.2 2.4]]


In [ ]:
print(x0l)
print(x1l)
print(x2l)
print(x0w)
print(x1w)
print(x2w)


[4.9 4.7 4.6 5.  5.4 4.6]
[6.4 6.9 5.5 6.5 5.7 6.3]
[5.6 5.1 5.6 5.9 5.3 5.7]
[3.  3.2 3.1 3.6 3.9 3.4]
[3.2 3.1 2.3 2.8 2.8 3.3]
[2.2 1.5 1.4 2.1 1.8 1.9]


In [ ]:
# Gaussian 

#Calculate the mean and variance length 0
mean_l0 = np.mean(x0l)
var_l0 = np.var(x0l)

#Calculate the mean and variance length 1
mean_l1 = np.mean(x1l)
var_l1 = np.var(x1l)

#Calculate the mean and variance of length x2
mean_l2 = np.mean(x2l)
var_l2 = np.var(x2l)

#Calculate the mean and variance width 0
mean_w0 = np.mean(x0w)
var_w0 = np.var(x0w)

#Calculate the mean and variance width 1
mean_w1 = np.mean(x1w)
var_w1 = np.var(x1w)

#Calculate the mean and variance of width x2
mean_w2 = np.mean(x2w)
var_w2 = np.var(x2w)

#length
print("Mean of length x0: ", mean_l0)
print("Variance of length x0: ", var_l0)
print("\n")
print("Mean of length x1: ", mean_l1)
print("Variance of length x1: ", var_l1)
print("\n")
print("Mean of length x2: ", mean_l2)
print("Variance of length x2: ", var_l2)
print("\n")
#width
print("Mean of width x0: ", mean_w0)
print("Variance of width x0: ", var_w0)
print("\n")
print("Mean of width x1: ", mean_w1)
print("Variance of width x1: ", var_w1)
print("\n")
print("Mean of width x2: ", mean_w2)
print("Variance of width x2: ", var_w2)
print("\n")


Mean of length x0:  4.866666666666667
Variance of length x0:  0.07888888888888902


Mean of length x1:  6.216666666666666
Variance of length x1:  0.22805555555555565


Mean of length x2:  5.533333333333332
Variance of length x2:  0.06888888888888899


Mean of width x0:  3.3666666666666667
Variance of width x0:  0.09555555555555552


Mean of width x1:  2.9166666666666674
Variance of width x1:  0.11138888888888894


Mean of width x2:  1.8166666666666667
Variance of width x2:  0.08472222222222225




In [ ]:
import math


In [ ]:
#Gaussian disstribution
tu0l= math.exp((-(X[:,0].copy()-mean_l0)**2)/(2*var_l0));
f0l= tu0l/math.sqrt(2*math.pi*var_l0)
tu0w= math.exp((-(X[:,1].copy()-mean_w0)**2)/(2*var_w0));
f0w= tu0w/math.sqrt(2*math.pi*var_w0)
tu1l= math.exp((-(X[:,0].copy()-mean_l1)**2)/(2*var_l1));
f1l= tu1l/math.sqrt(2*math.pi*var_l1)
tu1w= math.exp((-(X[:,1].copy()-mean_w1)**2)/(2*var_w1));
f1w= tu1w/math.sqrt(2*math.pi*var_w1)
tu2l= math.exp((-(X[:,0].copy()-mean_l2)**2)/(2*var_l2));
f2l= tu2l/math.sqrt(2*math.pi*var_l2)
tu2w= math.exp((-(X[:,1].copy()-mean_w2)**2)/(2*var_w2));
f2w= tu2w/math.sqrt(2*math.pi*var_w2)
print("Gaussian length x0: ", f0l)
print("Gaussian of width x0: ", f0w)
print("\n")
print("Gaussian length x1: ", f1l)
print("Gaussian of width x1: ", f1w)
print("\n")
print("Gaussian length x2: ", f2l)
print("Gaussian of width x2: ", f2w)
print("\n")

Gaussian length x0:  0.7023619270784218
Gaussian of width x0:  0.009711449940278253


Gaussian length x1:  0.08663993896437762
Gaussian of width x1:  0.3606565896070047


Gaussian length x2:  0.678575210966582
Gaussian of width x2:  0.1839766225878629




In [ ]:
P_lw0= f0l*f0w
print("P(length=5.2, width=2.4 | cat=0)= ", P_lw0)
print("\n")
P_lw1= f1l*f1w
print("P(length=5.2, width=2.4 | cat=1)= ", P_lw1)
print("\n")
P_lw2= f2l*f2w
print("P(length=5.2, width=2.4 | cat=2)", P_lw2)


P(length=5.2, width=2.4 | cat=0)=  0.006820952694779459


P(length=5.2, width=2.4 | cat=1)=  0.031247264910651475


P(length=5.2, width=2.4 | cat=2) 0.1248419754854783


In [ ]:
P0=P1=P2= 1/3


In [ ]:
P_lw= P_lw0*P0+ P_lw1*P1+P_lw2*P2
print(P_lw)

0.05430339769696974


In [ ]:
P0_lw= (P_lw0*P0)/P_lw
P1_lw= (P_lw1*P1)/P_lw
P2_lw= (P_lw2*P2)/P_lw
print("P(cat=0| length=5.2, width=2.4)= ", P0_lw)
print("\n")
print("P(cat=1| length=5.2, width=2.4)= ", P1_lw)
print("\n")
print("P(cat=0| length=5.2, width=2.4)= ", P2_lw)

P(cat=0| length=5.2, width=2.4)=  0.04186940402785689


P(cat=1| length=5.2, width=2.4)=  0.19180669004065617


P(cat=0| length=5.2, width=2.4)=  0.7663239059314869


In [ ]:
# Classification

max= P0_lw
if (P1_lw>max and P2_lw< max):
  max=P1_lw
  print("Conclusion: X belongs to Label 1")
if (P2_lw>max):
  max= P2_lw
  print("Conclusion: X belongs to Label 2")
else:
  print("Conclusion: X belongs to Label 0")


Conclusion: X belongs to Label 2
