<a href="https://colab.research.google.com/github/GiaHan2702/lab2/blob/main/ex2_stand.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import statistics as st

In [24]:
features = np.array([[4.9,     3], 
                    [4.7, 3.2], 
                    [4.6, 3.1], 
                    [5,  3.6], 
                    [5.4, 3.9],
                    [4.6, 3.4], 
                    [6.4, 3.2], 
                    [6.9,  3.1], 
                    [5.5, 2.3],  
                    [6.5, 2.8],         
                    [5.7, 2.8], 
                    [6.3, 3.3], 
                    [5.6,  2.2], 
                    [5.1, 1.5],
                    [5.6, 1.4], 
                    [5.9, 2.1], 
                    [5.3,  1.8],   
                    [5.7, 1.9]
                     ])

labels = np.array([[0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   ])

X = np.array([[5.2, 2.4]])

print(features)
print(labels)

[[4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [5.6 2.2]
 [5.1 1.5]
 [5.6 1.4]
 [5.9 2.1]
 [5.3 1.8]
 [5.7 1.9]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]


In [25]:
print(features[:,0])
print(features[:,1])

[4.9 4.7 4.6 5.  5.4 4.6 6.4 6.9 5.5 6.5 5.7 6.3 5.6 5.1 5.6 5.9 5.3 5.7]
[3.  3.2 3.1 3.6 3.9 3.4 3.2 3.1 2.3 2.8 2.8 3.3 2.2 1.5 1.4 2.1 1.8 1.9]


In [26]:
# Standardization 

#Calculate the mean and variance of feature x1
mean_x1 = np.mean(features[:, 0])
var_x1 = np.var(features[:, 0])


#Calculate the mean and variance of feature x2
mean_x2 = np.mean(features[:, 1])
var_x2 = np.var(features[:, 1])

print("Mean of feature x1: ", mean_x1)
print("Variance of feature x1: ", var_x1)
print("\n")
print("Mean of feature x2: ", mean_x2)
print("Variance of feature x2: ", var_x2)
print("\n")


Mean of feature x1:  5.538888888888889
Variance of feature x1:  0.4290432098765434


Mean of feature x2:  2.7
Variance of feature x2:  0.5211111111111112




In [27]:
# Standardize the given features

stand_features = features.copy()
stand_features[:, 0] = (features[:, 0].copy() - mean_x1) / np.sqrt(var_x1)

stand_features[:, 1] = (features[:, 1].copy() - mean_x2) / np.sqrt(var_x2)

print(stand_features)

[[-0.97538218  0.41558139]
 [-1.28071922  0.69263564]
 [-1.43338773  0.55410852]
 [-0.82271367  1.24674416]
 [-0.21203961  1.66232555]
 [-1.43338773  0.9696899 ]
 [ 1.31464555  0.69263564]
 [ 2.07798813  0.55410852]
 [-0.05937109 -0.55410852]
 [ 1.46731407  0.13852713]
 [ 0.24596594  0.13852713]
 [ 1.16197704  0.83116277]
 [ 0.09329743 -0.69263564]
 [-0.67004515 -1.66232555]
 [ 0.09329743 -1.80085268]
 [ 0.55130297 -0.83116277]
 [-0.36470812 -1.24674416]
 [ 0.24596594 -1.10821703]]


In [28]:
# Standardize the features of X
stand_X = X.copy()
stand_X[:, 0] = (X[:, 0].copy() - mean_x1) / np.sqrt(var_x1)
stand_X[:, 1] = (X[:, 1].copy() - mean_x2) / np.sqrt(var_x2)

print(stand_X)

[[-0.51737664 -0.41558139]]


In [29]:
# Calculate the features distance from 𝑋 to the data samples
d1 = stand_X.copy() - stand_features.copy() 
d2 = np.sqrt((d1[:, 0].copy()) ** 2  + (d1[:, 1].copy()) ** 2)

print(d1)
print(d2)

[[ 0.45800555 -0.83116277]
 [ 0.76334258 -1.10821703]
 [ 0.91601109 -0.9696899 ]
 [ 0.30533703 -1.66232555]
 [-0.30533703 -2.07790693]
 [ 0.91601109 -1.38527129]
 [-1.83202219 -1.10821703]
 [-2.59536477 -0.9696899 ]
 [-0.45800555  0.13852713]
 [-1.9846907  -0.55410852]
 [-0.76334258 -0.55410852]
 [-1.67935367 -1.24674416]
 [-0.61067406  0.27705426]
 [ 0.15266852  1.24674416]
 [-0.61067406  1.38527129]
 [-1.06867961  0.41558139]
 [-0.15266852  0.83116277]
 [-0.76334258  0.69263564]]
[0.94899981 1.34567339 1.33393209 1.69013518 2.10022092 1.66073865
 2.14113295 2.77059863 0.47849644 2.06059056 0.94325402 2.09155439
 0.67058323 1.2560568  1.51390203 1.14664031 0.84506759 1.03074538]


In [30]:
# Classification
# Choosing k for classification
k = 3
min_d = d2.argsort()[:k]

classify = labels[min_d] #extract the corresponding labels
print(classify)

# Find the mode label
print("Conclusion: X belongs to Label ", st.mode(classify[:,0]))

[[1]
 [2]
 [2]]
Conclusion: X belongs to Label  2
