<a href="https://colab.research.google.com/github/GiaHan2702/lab2/blob/main/ex2_c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

python code to verify part a

In [1]:
import numpy as np
import statistics as st

In [7]:
features = np.array([[4.9,     3], 
                    [4.7, 3.2], 
                    [4.6, 3.1], 
                    [5,  3.6], 
                    [5.4, 3.9],
                    [4.6, 3.4], 
                    [6.4, 3.2], 
                    [6.9,  3.1], 
                    [5.5, 2.3],  
                    [6.5, 2.8],         
                    [5.7, 2.8], 
                    [6.3, 3.3], 
                    [5.6,  2.2], 
                    [5.1, 1.5],
                    [5.6, 1.4], 
                    [5.9, 2.1], 
                    [5.3,  1.8],   
                    [5.7, 1.9]
                     ])
x0l=np.array([4.9, 4.7, 4.6, 5, 5.4,4.6])
x1l=np.array([6.4, 6.9, 5.5, 6.5, 5.7, 6.3])
x2l=np.array([5.6, 5.1, 5.6, 5.9, 5.3, 5.7])

x0w=np.array([3, 3.2, 3.1, 3.6, 3.9, 3.4])
x1w=np.array([3.2, 3.1, 2.3, 2.8, 2.8, 3.3])
x2w=np.array([2.2, 1.5, 1.4, 2.1, 1.8, 1.9])

labels = np.array([[0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   ])

X = np.array([[5.2, 2.4]])

print(features)
print(labels)
print(x0l)
print(X)

[[4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [5.6 2.2]
 [5.1 1.5]
 [5.6 1.4]
 [5.9 2.1]
 [5.3 1.8]
 [5.7 1.9]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
[4.9 4.7 4.6 5.  5.4 4.6]
[[5.2 2.4]]


In [10]:
print(x0l)
print(x1l)
print(x2l)
print(x0w)
print(x1w)
print(x2w)

[4.9 4.7 4.6 5.  5.4 4.6]
[6.4 6.9 5.5 6.5 5.7 6.3]
[5.6 5.1 5.6 5.9 5.3 5.7]
[3.  3.2 3.1 3.6 3.9 3.4]
[3.2 3.1 2.3 2.8 2.8 3.3]
[2.2 1.5 1.4 2.1 1.8 1.9]


In [13]:
#Calculate the mean length 0
mean_l0 = np.mean(x0l)

#Calculate the mean length 1
mean_l1 = np.mean(x1l)

#Calculate the mean length x2
mean_l2 = np.mean(x2l)

#Calculate the mean width 0
mean_w0 = np.mean(x0w)

#Calculate the mean width 1
mean_w1 = np.mean(x1w)

#Calculate the mean width x2
mean_w2 = np.mean(x2w)

#length
print("Mean of length x0: ", mean_l0)
print("\n")
print("Mean of length x1: ", mean_l1)
print("\n")
print("Mean of length x2: ", mean_l2)
print("\n")
#width
print("Mean of width x0: ", mean_w0)
print("\n")
print("Mean of width x1: ", mean_w1)
print("\n")
print("Mean of width x2: ", mean_w2)
print("\n")



Mean of length x0:  4.866666666666667


Mean of length x1:  6.216666666666666


Mean of length x2:  5.533333333333332


Mean of width x0:  3.3666666666666667


Mean of width x1:  2.9166666666666674


Mean of width x2:  1.8166666666666667




In [12]:
import math

In [16]:
distance1= math.sqrt(((X[:,0].copy())-mean_l0)**2 + (X[:,1]-mean_w0)**2)
print(distance1)
distance2= math.sqrt(((X[:,0].copy())-mean_l1)**2 + (X[:,1]-mean_w1)**2)
print(distance2)
distance3= math.sqrt(((X[:,0].copy())-mean_l2)**2 + (X[:,1]-mean_w2)**2)
print(distance3)

1.0225241100118645
1.140419026303733
0.6718548123582118


In [18]:
# Classification

min= distance1
if (distance2<min and distance3 > min):
  min=distance2
  print("Conclusion: X belongs to Label 1")
if (distance3<min):
  max= distance3
  print("Conclusion: X belongs to Label 2")
else:
  print("Conclusion: X belongs to Label 0")

Conclusion: X belongs to Label 2
