<a href="https://colab.research.google.com/github/GiaHan2702/lab2/blob/main/func_ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import statistics as st

In [ ]:
features = np.array([[7.24, 7.51, 21.17], 
                    [16.41, 8.29, 19.31], 
                    [17.04, 3.78, 22.11], 
                    [20.67, 0.76, 3.03], 
                    [20.31, 16.22, 15.85], 
                    [1.49, 16.1, 0.13],
                    [7.85, 18.27, 14.85],
                    [15.5, 14.14, 14.66]])

labels= np.array([[1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2]])

X = np.array([[14.92, 10.97, 8.78]])

print(features)
print(labels)

[[ 7.24  7.51 21.17]
 [16.41  8.29 19.31]
 [17.04  3.78 22.11]
 [20.67  0.76  3.03]
 [20.31 16.22 15.85]
 [ 1.49 16.1   0.13]
 [ 7.85 18.27 14.85]
 [15.5  14.14 14.66]]
[[1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]]


In [ ]:
print(features[:,0])
print(features[:,1])
print(features[:,2])

[ 7.24 16.41 17.04 20.67 20.31  1.49  7.85 15.5 ]
[ 7.51  8.29  3.78  0.76 16.22 16.1  18.27 14.14]
[21.17 19.31 22.11  3.03 15.85  0.13 14.85 14.66]


In [ ]:
# Standardization 

#Calculate the mean and variance of feature x1
mean_x1 = np.mean(features[:, 0])
var_x1 = np.var(features[:, 0])


#Calculate the mean and variance of feature x2
mean_x2 = np.mean(features[:, 1])
var_x2 = np.var(features[:, 1])

#Calculate the mean and variance of feature x3
mean_x3 = np.mean(features[:, 2])
var_x3 = np.var(features[:, 2])


print("Mean of feature x1: ", mean_x1)
print("Variance of feature x1: ", var_x1)
print("\n")
print("Mean of feature x2: ", mean_x2)
print("Variance of feature x2: ", var_x2)
print("\n")
print("Mean of feature x3: ", mean_x3)
print("Variance of feature x3: ", var_x3)


Mean of feature x1:  13.313749999999999
Variance of feature x1:  42.2321734375


Mean of feature x2:  10.63375
Variance of feature x2:  36.4259984375


Mean of feature x3:  13.88875
Variance of feature x3:  57.8220609375


In [ ]:
# Standardize the given features

stand_features = features.copy()
stand_features[:, 0] = (features[:, 0].copy() - mean_x1) / np.sqrt(var_x1)

stand_features[:, 1] = (features[:, 1].copy() - mean_x2) / np.sqrt(var_x2)

stand_features[:, 2] = (features[:, 2].copy() - mean_x3) / np.sqrt(var_x3)

print(stand_features)


[[-0.93462027 -0.51757172  0.95754493]
 [ 0.47644668 -0.38833412  0.71293946]
 [ 0.57339021 -1.13559253  1.08116274]
 [ 1.1319696  -1.63597399 -1.42801593]
 [ 1.0765733   0.92558144  0.25792068]
 [-1.81942234  0.90569873 -1.80939004]
 [-0.84075431  1.26524435  0.12641237]
 [ 0.33641713  0.58094785  0.10142579]]


In [ ]:
# Standardize the features of X
stand_X = X.copy()
stand_X[:, 0] = (X[:, 0].copy() - mean_x1) / np.sqrt(var_x1)
stand_X[:, 1] = (X[:, 1].copy() - mean_x2) / np.sqrt(var_x2)
stand_X[:, 2] = (X[:, 2].copy() - mean_x3) / np.sqrt(var_x3)

print(stand_X)

[[ 0.24716753  0.055713   -0.67184311]]


In [ ]:
# Normalize the given features

normal_features = features.copy()
normal_features[:, 0] = (features[:, 0].copy() - min(features[:, 0].copy())) / (max(features[:, 0].copy())-min(features[:, 0].copy()))

normal_features[:, 1] = (features[:, 1].copy() - min(features[:, 1].copy())) / (max(features[:, 1].copy())-min(features[:, 1].copy()))

normal_features[:, 2] = (features[:, 2].copy() - min(features[:, 2].copy())) / (max(features[:, 2].copy())-min(features[:, 2].copy()))

print(normal_features)


[[0.29979145 0.385494   0.95723385]
 [0.77789364 0.43003998 0.87261146]
 [0.81074035 0.17247287 1.        ]
 [1.         0.         0.13193813]
 [0.98123045 0.88292404 0.71519563]
 [0.         0.87607082 0.        ]
 [0.33159541 1.         0.66969973]
 [0.73044838 0.76413478 0.66105551]]


In [ ]:
# Normalize the features of X
normal_X = X.copy()
normal_X[:, 0] = (X[:, 0].copy() - min(features[:, 0].copy())) / (max(features[:, 0].copy())-min(features[:, 0].copy()))
normal_X[:, 1] = (X[:, 1].copy() - min(features[:, 1].copy())) / (max(features[:, 1].copy())-min(features[:, 1].copy()))
normal_X[:, 2] =(X[:, 2].copy() - min(features[:, 2].copy())) / (max(features[:, 2].copy())-min(features[:, 2].copy()))
print(normal_X)

[[0.70020855 0.58309537 0.39353958]]


In [ ]:
# Calculate the features distance from 𝑋 to the data samples
d1 = stand_X.copy() - stand_features.copy() 
d2 = np.sqrt((d1[:, 0].copy()) ** 2  + (d1[:, 1].copy()) ** 2 +(d1[:, 2].copy()) ** 2)

print(d1)
print(d2)

[[ 1.1817878   0.57328472 -1.62938803]
 [-0.22927914  0.44404712 -1.38478257]
 [-0.32622268  1.19130553 -1.75300585]
 [-0.88480207  1.69168699  0.75617282]
 [-0.82940576 -0.86986843 -0.92976379]
 [ 2.06658987 -0.84998573  1.13754693]
 [ 1.08792185 -1.20953135 -0.79825548]
 [-0.0892496  -0.52523484 -0.7732689 ]]
[2.09288871 1.47219888 2.14444856 2.05340617 1.51955445 2.5074454
 1.81211253 0.93903244]


In [ ]:
# Calculate the features distance from 𝑋 to the data samples
d1 = normal_X.copy() - normal_features.copy() 
d2 = np.sqrt((d1[:, 0].copy()) ** 2  + (d1[:, 1].copy()) ** 2 +(d1[:, 2].copy()) ** 2)

print(d1)
print(d2)

[[ 0.4004171   0.19760137 -0.56369427]
 [-0.07768509  0.1530554  -0.47907188]
 [-0.1105318   0.4106225  -0.60646042]
 [-0.29979145  0.58309537  0.26160146]
 [-0.2810219  -0.29982867 -0.32165605]
 [ 0.70020855 -0.29297544  0.39353958]
 [ 0.36861314 -0.41690463 -0.27616015]
 [-0.03023983 -0.18103941 -0.26751592]]
[0.71911848 0.50889173 0.74069046 0.70591108 0.52185549 0.8549854
 0.62124837 0.32442947]


In [ ]:

def def_standard(featuress):
    """Function compute standardlize """
    std_features = featuress.copy()
    for i in range(featuress.shape[1]):
      #Compute mean and var of each column
      mean_x = np.mean(features[:,i].copy())
      var_x = np.var(features[:,i].copy())

      #Compute standardize of each column
      std_features[:,i] = (featuress[:,i].copy() - mean_x)/ np.sqrt(var_x)
    return std_features

In [ ]:

def def_normal(featuress):
    """Function compute normalize """
    nor_features = featuress.copy()
    for i in range(featuress.shape[1]):
      #Find max and min of each column
      max_val = max(features[:,i].copy())
      min_val = min(features[:,i].copy())

      #Compute normalize of each column
      nor_features[:,i] = (featuress[:,i].copy() - min_val)/(max_val - min_val)
    return nor_features

In [ ]:
#Compute Standardize features and X
std = def_standard(features)
std_X = def_standard(X)
print("Standardize features:")
print(std)

print(f"\nStandardization of X = {std_X}")

#Compute Normalize features and X
nor = def_normal(features)
norX = def_normal(X)
print("\nNormalize features:")
print(nor)

print(f"\nNormalization of X = {norX}")

Standardize features:
[[-0.93462027 -0.51757172  0.95754493]
 [ 0.47644668 -0.38833412  0.71293946]
 [ 0.57339021 -1.13559253  1.08116274]
 [ 1.1319696  -1.63597399 -1.42801593]
 [ 1.0765733   0.92558144  0.25792068]
 [-1.81942234  0.90569873 -1.80939004]
 [-0.84075431  1.26524435  0.12641237]
 [ 0.33641713  0.58094785  0.10142579]]

Standardization of X = [[ 0.24716753  0.055713   -0.67184311]]

Normalize features:
[[0.29979145 0.385494   0.95723385]
 [0.77789364 0.43003998 0.87261146]
 [0.81074035 0.17247287 1.        ]
 [1.         0.         0.13193813]
 [0.98123045 0.88292404 0.71519563]
 [0.         0.87607082 0.        ]
 [0.33159541 1.         0.66969973]
 [0.73044838 0.76413478 0.66105551]]

Normalization of X = [[0.70020855 0.58309537 0.39353958]]


In [ ]:
#Distance of standardize features
d1_stand = std - std_X
d2_stand = np.sqrt((d1_stand[:, 0].copy()) ** 2  + (d1_stand[:, 1].copy()) ** 2 + (d1_stand[:, 2].copy()) ** 2)
print("Standardized distances:")
print(d2_stand)

#Distance by normalize
d1_nor = nor - norX
d2_nor = np.sqrt((d1_nor[:, 0].copy()) ** 2  + (d1_nor[:, 1].copy()) ** 2 + (d1_nor[:, 2].copy()) ** 2)
print("Normalized distances:")
print(d2_nor)

Standardized distances:
[2.09288871 1.47219888 2.14444856 2.05340617 1.51955445 2.5074454
 1.81211253 0.93903244]
Normalized distances:
[0.71911848 0.50889173 0.74069046 0.70591108 0.52185549 0.8549854
 0.62124837 0.32442947]


In [ ]:
def my_knn(featuress, labels, k = 3, scaling_method = "Standardization"):
    ans = featuress[:-1,:].copy()
    """This function compute minimum distance and return label corresponding to smaller labels set"""
    key = featuress[-1:,:].copy()
    if scaling_method == "Standardization":
        X_scale = def_standard(key)
        feat_scale = def_standard(ans)
    if scaling_method == "Normalization":
        X_scale = def_normal(key)
        feat_scale = def_normal(ans)
    #else:
     # print("Scaling method is invalid")
     # return -1
    
    #Compute distance of X with each feature
    diff = feat_scale - X_scale
    diff_whole = np.sqrt((diff[:, 0].copy()) ** 2  + (diff[:, 1].copy()) ** 2 + (diff[:, 2].copy()) ** 2)
    #print(diff_whole)

    #Find the kth smallest distance
    min_d = diff_whole.argsort()[:k]
    #Classify labels
    classify = labels[min_d]
    #print(classify)
    #print(f"Features with X = {key_X}, scaling method = {scaling_method} and K = {k}:")
    #print(f"X has labels = {classify[:,0]}, belongs to Label {st.mode(classify[:,0])}\n")
    # Find the mode label
    print("Conclusion: X belongs to Label ", st.mode(classify[:,0]))
    return st.mode(classify[:,0])

In [ ]:
def choose(featuress, X):
    return np.concatenate((featuress.copy(), X.copy()), axis = 0)

In [ ]:
whole_features = choose(features,X)

knn_std = my_knn(whole_features, labels, k = 3, scaling_method = "Standardization")
knn_nor = my_knn(whole_features, labels, k = 3, scaling_method = "Normalization")




Conclusion: X belongs to Label  2
Conclusion: X belongs to Label  2
