<a href="https://colab.research.google.com/github/GiaHan2702/lab2/blob/main/lab2_ex1b_normalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import statistics as st
features = np.array([[7.24, 7.51, 21.17], 
                    [16.41, 8.29, 19.31], 
                    [17.04, 3.78, 22.11], 
                    [20.67, 0.76, 3.03], 
                    [20.31, 16.22, 15.85], 
                    [1.49, 16.1, 0.13],
                    [7.85, 18.27, 14.85],
                    [15.5, 14.14, 14.66]])

labels = np.array([[1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2]])

X = np.array([[14.92, 10.97, 8.78]])

print(features)
print(labels)
features = np.array([[7.24, 7.51, 21.17], 
                    [16.41, 8.29, 19.31], 
                    [17.04, 3.78, 22.11], 
                    [20.67, 0.76, 3.03], 
                    [20.31, 16.22, 15.85], 
                    [1.49, 16.1, 0.13],
                    [7.85, 18.27, 14.85],
                    [15.5, 14.14, 14.66]])

labels = np.array([[1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2]])

X = np.array([[14.92, 10.97, 8.78]])

print(features)
print(labels)


[[ 7.24  7.51 21.17]
 [16.41  8.29 19.31]
 [17.04  3.78 22.11]
 [20.67  0.76  3.03]
 [20.31 16.22 15.85]
 [ 1.49 16.1   0.13]
 [ 7.85 18.27 14.85]
 [15.5  14.14 14.66]]
[[1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]]
[[ 7.24  7.51 21.17]
 [16.41  8.29 19.31]
 [17.04  3.78 22.11]
 [20.67  0.76  3.03]
 [20.31 16.22 15.85]
 [ 1.49 16.1   0.13]
 [ 7.85 18.27 14.85]
 [15.5  14.14 14.66]]
[[1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]]


In [3]:

print(features[:,0])

print(features[:,1])

print(features[:,2])


[ 7.24 16.41 17.04 20.67 20.31  1.49  7.85 15.5 ]
[ 7.51  8.29  3.78  0.76 16.22 16.1  18.27 14.14]
[21.17 19.31 22.11  3.03 15.85  0.13 14.85 14.66]


In [4]:
# Normalize the given features

normal_features = features.copy()
normal_features[:, 0] = (features[:, 0].copy() - min(features[:, 0].copy())) / (max(features[:, 0].copy())-min(features[:, 0].copy()))

normal_features[:, 1] = (features[:, 1].copy() - min(features[:, 1].copy())) / (max(features[:, 1].copy())-min(features[:, 1].copy()))

normal_features[:, 2] = (features[:, 2].copy() - min(features[:, 2].copy())) / (max(features[:, 2].copy())-min(features[:, 2].copy()))

print(normal_features)


[[0.29979145 0.385494   0.95723385]
 [0.77789364 0.43003998 0.87261146]
 [0.81074035 0.17247287 1.        ]
 [1.         0.         0.13193813]
 [0.98123045 0.88292404 0.71519563]
 [0.         0.87607082 0.        ]
 [0.33159541 1.         0.66969973]
 [0.73044838 0.76413478 0.66105551]]


In [8]:
# Normalize the features of X
normal_X = X.copy()
normal_X[:, 0] = (X[:, 0].copy() - min(features[:, 0].copy())) / (max(features[:, 0].copy())-min(features[:, 0].copy()))
normal_X[:, 1] = (X[:, 1].copy() - min(features[:, 1].copy())) / (max(features[:, 1].copy())-min(features[:, 1].copy()))
normal_X[:, 2] =(X[:, 2].copy() - min(features[:, 2].copy())) / (max(features[:, 2].copy())-min(features[:, 2].copy()))
print(normal_X)

[[0.70020855 0.58309537 0.39353958]]


In [9]:
# Calculate the features distance from 𝑋 to the data samples
d1 = normal_X.copy() - normal_features.copy() 
d2 = np.sqrt((d1[:, 0].copy()) ** 2  + (d1[:, 1].copy()) ** 2 +(d1[:, 2].copy()) ** 2)

print(d1)
print(d2)


[[ 0.4004171   0.19760137 -0.56369427]
 [-0.07768509  0.1530554  -0.47907188]
 [-0.1105318   0.4106225  -0.60646042]
 [-0.29979145  0.58309537  0.26160146]
 [-0.2810219  -0.29982867 -0.32165605]
 [ 0.70020855 -0.29297544  0.39353958]
 [ 0.36861314 -0.41690463 -0.27616015]
 [-0.03023983 -0.18103941 -0.26751592]]
[0.71911848 0.50889173 0.74069046 0.70591108 0.52185549 0.8549854
 0.62124837 0.32442947]


In [10]:
# Classification
# Choosing k for classification
k = 3
min_d = d2.argsort()[:k]

classify = labels[min_d] #extract the corresponding labels
print(classify)

# Find the mode label
print("Conclusion: X belongs to Label ", st.mode(classify[:,0]))

[[2]
 [1]
 [2]]
Conclusion: X belongs to Label  2
