<a href="https://colab.research.google.com/github/GiaHan2702/lab2/blob/main/lab2_ex1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

lab2_ex1b.

In [1]:
import numpy as np
import statistics as st

In [2]:
features = np.array([[7.24, 7.51, 21.17], 
                    [16.41, 8.29, 19.31], 
                    [17.04, 3.78, 22.11], 
                    [20.67, 0.76, 3.03], 
                    [20.31, 16.22, 15.85], 
                    [1.49, 16.1, 0.13],
                    [7.85, 18.27, 14.85],
                    [15.5, 14.14, 14.66]])

labels = np.array([[1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2]])

X = np.array([[14.92, 10.97, 8.78]])

print(features)
print(labels)

[[ 7.24  7.51 21.17]
 [16.41  8.29 19.31]
 [17.04  3.78 22.11]
 [20.67  0.76  3.03]
 [20.31 16.22 15.85]
 [ 1.49 16.1   0.13]
 [ 7.85 18.27 14.85]
 [15.5  14.14 14.66]]
[[1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]]


In [3]:
print(features[:,0])

[ 7.24 16.41 17.04 20.67 20.31  1.49  7.85 15.5 ]


In [6]:
# Standardization 

#Calculate the mean and variance of feature x1
mean_x1 = np.mean(features[:, 0])
var_x1 = np.var(features[:, 0])


#Calculate the mean and variance of feature x2
mean_x2 = np.mean(features[:, 1])
var_x2 = np.var(features[:, 1])

#Calculate the mean and variance of feature x3
mean_x3 = np.mean(features[:, 2])
var_x3 = np.var(features[:, 2])


print("Mean of feature x1: ", mean_x1)
print("Variance of feature x1: ", var_x1)
print("\n")
print("Mean of feature x2: ", mean_x2)
print("Variance of feature x2: ", var_x2)
print("\n")
print("Mean of feature x3: ", mean_x3)
print("Variance of feature x3: ", var_x3)


Mean of feature x1:  13.313749999999999
Variance of feature x1:  42.2321734375


Mean of feature x2:  10.63375
Variance of feature x2:  36.4259984375


Mean of feature x3:  13.88875
Variance of feature x3:  57.8220609375


In [7]:
# Standardize the given features

stand_features = features.copy()
stand_features[:, 0] = (features[:, 0].copy() - mean_x1) / np.sqrt(var_x1)

stand_features[:, 1] = (features[:, 1].copy() - mean_x2) / np.sqrt(var_x2)

stand_features[:, 2] = (features[:, 2].copy() - mean_x3) / np.sqrt(var_x3)

print(stand_features)


[[-0.93462027 -0.51757172  0.95754493]
 [ 0.47644668 -0.38833412  0.71293946]
 [ 0.57339021 -1.13559253  1.08116274]
 [ 1.1319696  -1.63597399 -1.42801593]
 [ 1.0765733   0.92558144  0.25792068]
 [-1.81942234  0.90569873 -1.80939004]
 [-0.84075431  1.26524435  0.12641237]
 [ 0.33641713  0.58094785  0.10142579]]


In [8]:
# Standardize the features of X
stand_X = X.copy()
stand_X[:, 0] = (X[:, 0].copy() - mean_x1) / np.sqrt(var_x1)
stand_X[:, 1] = (X[:, 1].copy() - mean_x2) / np.sqrt(var_x2)
stand_X[:, 2] = (X[:, 2].copy() - mean_x3) / np.sqrt(var_x3)

print(stand_X)

[[ 0.24716753  0.055713   -0.67184311]]


In [9]:
# Calculate the features distance from 𝑋 to the data samples
d1 = stand_X.copy() - stand_features.copy() 
d2 = np.sqrt((d1[:, 0].copy()) ** 2  + (d1[:, 1].copy()) ** 2 +(d1[:, 2].copy()) ** 2)

print(d1)
print(d2)

[[ 1.1817878   0.57328472 -1.62938803]
 [-0.22927914  0.44404712 -1.38478257]
 [-0.32622268  1.19130553 -1.75300585]
 [-0.88480207  1.69168699  0.75617282]
 [-0.82940576 -0.86986843 -0.92976379]
 [ 2.06658987 -0.84998573  1.13754693]
 [ 1.08792185 -1.20953135 -0.79825548]
 [-0.0892496  -0.52523484 -0.7732689 ]]
[2.09288871 1.47219888 2.14444856 2.05340617 1.51955445 2.5074454
 1.81211253 0.93903244]


In [10]:
# Classification
# Choosing k for classification
k = 3
min_d = d2.argsort()[:k]

classify = labels[min_d] #extract the corresponding labels
print(classify)

# Find the mode label
print("Conclusion: X belongs to Label ", st.mode(classify[:,0]))

[[2]
 [1]
 [2]]
Conclusion: X belongs to Label  2
