<a href="https://colab.research.google.com/github/GiaHan2702/lab2/blob/main/lab2_ex2_func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import statistics as st

In [ ]:
features_set= np.array([[4.9,     3], 
                    [4.7, 3.2], 
                    [4.6, 3.1], 
                    [5,  3.6], 
                    [5.4, 3.9],
                    [4.6, 3.4], 
                    [6.4, 3.2], 
                    [6.9,  3.1], 
                    [5.5, 2.3],  
                    [6.5, 2.8],         
                    [5.7, 2.8], 
                    [6.3, 3.3], 
                    [5.6,  2.2], 
                    [5.1, 1.5],
                    [5.6, 1.4], 
                    [5.9, 2.1], 
                    [5.3,  1.8],   
                    [5.7, 1.9]
                     ])
x0l=np.array([4.9, 4.7, 4.6, 5, 5.4,4.6])
x1l=np.array([6.4, 6.9, 5.5, 6.5, 5.7, 6.3])
x2l=np.array([5.6, 5.1, 5.6, 5.9, 5.3, 5.7])

x0w=np.array([3, 3.2, 3.1, 3.6, 3.9, 3.4])
x1w=np.array([3.2, 3.1, 2.3, 2.8, 2.8, 3.3])
x2w=np.array([2.2, 1.5, 1.4, 2.1, 1.8, 1.9])

labels_set = np.array([[0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [0],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [1],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   [2],
                   ])

X_feature = np.array([[5.2, 2.4]])

print(features_set)
print(labels_set)
print(x0l)
print(X_feature)

[[4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [5.6 2.2]
 [5.1 1.5]
 [5.6 1.4]
 [5.9 2.1]
 [5.3 1.8]
 [5.7 1.9]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
[4.9 4.7 4.6 5.  5.4 4.6]
[[5.2 2.4]]


In [ ]:
print(x0l)
print(x1l)
print(x2l)
print(x0w)
print(x1w)
print(x2w)

[4.9 4.7 4.6 5.  5.4 4.6]
[6.4 6.9 5.5 6.5 5.7 6.3]
[5.6 5.1 5.6 5.9 5.3 5.7]
[3.  3.2 3.1 3.6 3.9 3.4]
[3.2 3.1 2.3 2.8 2.8 3.3]
[2.2 1.5 1.4 2.1 1.8 1.9]


In [ ]:
#Calculate the mean length 0
mean_l0 = np.mean(x0l)

#Calculate the mean length 1
mean_l1 = np.mean(x1l)

#Calculate the mean length x2
mean_l2 = np.mean(x2l)

#Calculate the mean width 0
mean_w0 = np.mean(x0w)

#Calculate the mean width 1
mean_w1 = np.mean(x1w)

#Calculate the mean width x2
mean_w2 = np.mean(x2w)

#length
print("Mean of length x0: ", mean_l0)
print("\n")
print("Mean of length x1: ", mean_l1)
print("\n")
print("Mean of length x2: ", mean_l2)
print("\n")
#width
print("Mean of width x0: ", mean_w0)
print("\n")
print("Mean of width x1: ", mean_w1)
print("\n")
print("Mean of width x2: ", mean_w2)
print("\n")


Mean of length x0:  4.866666666666667


Mean of length x1:  6.216666666666666


Mean of length x2:  5.533333333333332


Mean of width x0:  3.3666666666666667


Mean of width x1:  2.9166666666666674


Mean of width x2:  1.8166666666666667




In [ ]:
def def_mean(features):
  sum = 0
  for i in range(len(features)):
    sum = sum + features[i]
  return sum/len(features)

In [ ]:

def def_euclidean(a, b):
  """This function compute euclidean distance"""
  diff = a - b
  diff_whole = np.sqrt((diff[:, 0].copy()) ** 2  + (diff[:, 1].copy()) ** 2)
  return diff_whole
def def_manhattan(a, b):
  """This function compute manhattan distance"""
  diff = a - b
  diff_whole = np.abs(diff[:, 0].copy())   + np.abs(diff[:, 1].copy())
  return diff_whole

In [ ]:
#smallest distance classifier using Euclidean distance
eucli_dis = def_euclidean(features_set.copy(), X_feature.copy())
#smallest distance classifier using Manhattan  distance
manhat_dis = def_manhattan(features_set.copy(), X_feature.copy())

print("Euclidean distance")
print(eucli_dis)

print("Manhattan distance")
print(manhat_dis)

Euclidean distance
[0.67082039 0.94339811 0.92195445 1.21655251 1.5132746  1.16619038
 1.44222051 1.83847763 0.31622777 1.36014705 0.64031242 1.42126704
 0.4472136  0.90553851 1.07703296 0.76157731 0.60827625 0.70710678]
Manhattan distance
[0.9 1.3 1.3 1.4 1.7 1.6 2.  2.4 0.4 1.7 0.9 2.  0.6 1.  1.4 1.  0.7 1. ]


In [ ]:
def concat_features(features, X_key):
    """Concatenate array X into array features"""
    return np.concatenate((features.copy(), X_key.copy()), axis = 0)

In [ ]:
#Find mean of features set
features_mean_0 = def_mean(features_set[:6,:])
features_mean_1 = def_mean(features_set[6:12,:])
features_mean_2 = def_mean(features_set[12:18,:])

features_mean = concat_features(features_mean_0,features_mean_1)
features_mean = concat_features(features_mean,features_mean_2)
features_mean = np.reshape(features_mean, (3,2))
print("Mean of the features:")
print(features_mean)

smallest_dis = def_euclidean(features_mean, X_feature)
print("Smallest distance of features:")
print(smallest_dis)


Mean of the features:
[[4.86666667 3.36666667]
 [6.21666667 2.91666667]
 [5.53333333 1.81666667]]
Smallest distance of features:
[1.02252411 1.14041903 0.67185481]


In [ ]:
def my_sdc(features, labels, distance_type = "Euclidean distance"):
    """This function compute smallest dist"""
    feat = features[:-1,:].copy()
    key_X = features[-1:,:].copy()
    mean_0 = def_mean(feat[:6,:])
    mean_1 = def_mean(feat[6:12,:])
    mean_2 = def_mean(feat[12:18,:])

    mean_01 = concat_features(mean_0,mean_1)
    mean_012 = concat_features(mean_01,mean_2)
    mean = np.reshape(mean_012, (3,2))
    #print(mean)
    if distance_type == "Euclidean distance":
        result = def_euclidean(mean, key_X)
    elif distance_type == "Manhattan distance":
        result = def_manhattan(mean, key_X)
    else:
        print("Invalid distance_type")
        return -1
    #print(result)
    min_d = result.argsort()[0]
    #print(min_d)
      # Find the mode label
    classify = min_d
    print("Conclusion: X belongs to Label ", min_d)
    return classify
    

In [ ]:
features_new = concat_features(features_set, X_feature)

class_euclidean = my_sdc(features_new, labels_set, distance_type = "Euclidean distance")
class_manhattan = my_sdc(features_new, labels_set, distance_type = "Manhattan distance")

Conclusion: X belongs to Label  2
Conclusion: X belongs to Label  2
